# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
language: go

# Version of go to use
go:
  - "1.15.x"

# Define global variables
env:
  - GOARCH=amd64

# Use a matrix to define SO and possible future changes
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

# Install necessaries go packages
install:
  - make install
  - make install-gfx-deps
  - make install-linters

# Build, test & run cx test
script:
  - make build-full
  - make test
  - make test-full
  - make lint

# Notifications to Telegram channel
notifications:
  email: false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
