# Travis build configuration
# https://docs.travis-ci.com/user/customizing-the-build/
language: go

# Version of go to use
go:
  - "1.15.x"

# Define global variables
env:
  - GOARCH=amd64

addons:
  apt:
    packages:
    - make
    - glade
    - xvfb
    - libxinerama-dev 
    - libxcursor-dev
    - libxrandr-dev
    - libgl1-mesa-dev
    - libxi-dev
    - libperl-dev
    - libcairo2-dev
    - libpango1.0-dev
    - libglib2.0-dev
    - libopenal-dev
    - libxxf86vm-dev

# Use a matrix to define SO and possible future changes
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

# Build, test & run cx test
script:
  - make build
  - make install
  - make test

# Notifications to Telegram channel
notifications:
  email: false
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
